I try to load a dataset using the datasets python module in my local Python Notebook. I am running a Python 3.10.13 kernel as I do for my virtual environment. I cannot load the datasets I am following from a tutorial. Here's the error: How do I resolve ? I don't understand how this error is applicable, given that the dataset is something I am fetching and thus cannot be cached in my LocalFileSystem in the first place. Try doing: This error stems from a breaking change in fsspec. It has been fixed in the latest datasets release (2.14.6). Updating the installation with pip install -U datasets should fix the issue. git link : https://github.com/huggingface/datasets/issues/6352 if you are using fsspec then do: There is a problem with fsspec==2023.10.0 git link : https://github.com/huggingface/datasets/issues/6330