get error get model backref relat data call ca call io attempt unexpect place background error http import uuid import emailtyp timestamp uuidtyp sqlalchemi import boolean column foreignkey string uniqueconstraint import relationship import base class user base timestamp user id column uuidtyp name column string email column emailtyp column string column boolean def self return f user class compani base timestamp compani id column uuidtyp name column string column boolean def self return f compani class companyus base timestamp uniqueconstraint id column uuidtyp column uuidtyp foreignkey cascad compani relationship compani subqueri column uuidtyp foreignkey cascad user relationship user subqueri role column string def self return f companyus type import import asyncsess import declarativebas import set str class base declarativebas id fastapi import apirout sqlalchemi import select import currentasyncsess import currentus import user import userschema router apirout async def user currentus session currentasyncsess userschema print tri also user await user print return user point use schema found even print router work solut problem flask sync sqlalchemi sqlalchemi